<?php

abstract class AliquotTrackingItems extends BasicEnum {
    const SHIPMENT_REF = 'SHIPMENT_REF';
    const ALIQUOTS_ARRAY = 'ALIQUOTS_ARRAY';
    const ALIQUOT_ID = 'ALIQUOT_ID';
    const ALIQUOT_CREATION_DATE = 'ALIQUOT_CREATION_DATE';
    const ALIQUOT_LOCATION = 'CURRENT_ALIQUOT_LOCATION';
    const ALIQUOT_STATUS = 'CURRENT_ALIQUOT_STATUS';
    const ALIQUOT_DAMAGE = 'CURRENT_ALIQUOT_DAMAGE';
    const ALIQUOT_SHIPMENT_REF = 'CURRENT_ALIQUOT_SHIPMENT_REF';
    const FINAL_ALIQUOT_LOCATION = 'FINAL_ALIQUOT_LOCATION';
    const FINAL_ALIQUOT_STATUS = 'FINAL_ALIQUOT_STATUS';
    const FINAL_ALIQUOT_DAMAGE = 'FINAL_ALIQUOT_DAMAGE';
    const FINAL_ALIQUOT_SHIPMENT_REF = 'FINAL_ALIQUOT_SHIPMENT_REF';
    const INCLUDE_IN_SHIPMENT = 'INCLUDE_IN_SHIPMENT';
    const ALIQUOT_USED_FOR_EXOSOMES = 'USED';
    const EXOSOMES_SUCCESS = 'SUCCESS';
}